import "dotenv/config";
import express from "express";
import cors from "cors";
import mentorRouter from "./routes/mentor.route.js";
import errorMiddleware from "./middlewares/error.middleware.js";
const app = express();
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use("/api/v1/mentor", mentorRouter);
app.use(errorMiddleware);
export default app;
